import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {NextUIProvider} from "@nextui-org/react";

const inter = Inter({ subsets: ['latin'] })
const finalClass = `${inter.className} w-full h-full`

export const metadata: Metadata = {
  title: 'Next.js Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className='h-full'>
      <body className={finalClass}>
        <div className='bg-green-900 bg-fixed min-h-full flex justify-center'>
            {children}
        </div>
      </body>
    </html>
  )
}
